### ISSUE TITLE
WebSite not available

### ISSUE THREAD

**Issue by acabra85** [jirislav/Insanity#1]
http://insanity.jkozlovsky.cz/?play website is not available 
![image](https://cloud.githubusercontent.com/assets/6214865/22542543/930a9a42-e92c-11e6-8e8b-47c9908df137.png)

**Comment by jirislav** [comment]
Sorry about the delay, but I've completely forgotten about this game :) .. It is fixed now.

**Comment by acabra85** [comment]
Hi, thanks I've completely forgot how i got the link to your game but now i was able to play, really cool thanks for the fix
